### ISSUE TITLE
i got this error plx help

### ISSUE THREAD

**Issue by jayde007** [mbaker92/RaspPi-Code#1]
Traceback (most recent call last):
  File "push.py", line 12, in <module>
    camera.start_recording('/home/pi/Documents/Video/' + datetime.datetime.now().strftime('%Y-%m-%d%H:%M:%S') +'.h264')
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1049, in start_recording
    encoder.start(output, options.get('motion_output'))
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 812, in start
    super(PiVideoEncoder, self).start(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 375, in start
    self._open_output(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 331, in _open_output
    self.outputs[key] = mo.open_stream(output)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 344, in open_stream
    stream = io.open(stream, 'wb' if output else 'rb', buffering)
IOError: [Errno 2] No such file or directory: '/home/pi/Documents/Video/2019-04-0615:59:31.h264'

**Comment by mbaker92** [comment]
I just tried to replicate the error using a fresh Pi. I used my Raspberry Pi Zero W to test the code and found the problem.

You need to create a Video folder in your Documents directory for the code to work as is. You could also change the code by changing the camera.start_recording line to a directory that exists on your pi.

**Comment by jayde007** [comment]
I got it tnx
